[package]
name = "CUBIC_Config"
version = "0.1.0"
authors = ["CUB3D <callumthom11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-web = "1.0.5"
actix-files = "0.1.4"
json = "0.11.14"
futures = "0.1.28"
tokio = "0.1.22"

env_logger = "0.6.2"
log = "0.4.0"

diesel = { version = "1.4.2", default-features = false, features = ["sqlite"]}
dotenv = "0.14.1"
serde = { version = "1.0.98", features = ["derive"] }
uuid = {version = "0.7.4", default-features = false, features = ["v4"]}
#askama = "0.8.0"