name: Rust

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download cert
      run: wget https://cdn.cub3d.pw/auth/public.pem && openssl rsa -pubin -inform PEM -in public.pem -outform DER -out public.der
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Run clippy
      run: cargo clippy --all --tests --all-features
    - name: Check formatting
      run: cargo fmt -- --check
